### ISSUE TITLE
Support for HostRegexp() rule

### ISSUE THREAD

**Issue by mamiu** [borchero/switchboard#1]
@borchero It would be great to support the `HostRegexp()` [rule](https://doc.traefik.io/traefik/routing/routers/#rule).

Unfortunately switchboard can't generate a certificate for every possible string that would match the `HostRegexp()` rule, so we need a different approach here.

Since Traefik already has a syntax to provide domain names for certificates (via `spec.tls.domains`) it would be great if switchboard supported domains listet in the [`spec.tls.domains` section](https://doc.traefik.io/traefik/routing/routers/#domains) as well (especially when there's no `Host()` rule provided).

For example:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: foo
  namespace: bar
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`{www:(www.)?}example.{tld:(com|net)}`)
    services:
    - name: example-website
      port: 8080
  tls:
    secretName: supersecret
    domains:
    - main: example.com
      sans:
      - example.net
      - www.example.com
      - www.example.net
```

Do you switchboard could support such `IngressRoute`s as well?

---
And once again:
Echt hammer Projekt! Vielen Dank dafür.
Werds auf jeden Fall diese oder nächste Woche mal ausprobieren.
Schöne Grüße aus Australien.
