### ISSUE TITLE
Chart not found when installing as a dependency

### ISSUE THREAD

**Issue by AlexGodbehere** [borchero/switchboard#132]
I'm pulling in Switchboard as a subchart to my own chart with the following:

```yaml
- name: switchboard
  version: 0.5.8
  repository: oci://ghcr.io/borchero/charts/switchboard
  condition: switchboard.enabled
```

When I run `helm dependency update` I receive the following error:

```
Error: could not download oci://ghcr.io/borchero/charts/switchboard/switchboard: ghcr.io/borchero/charts/switchboard/switchboard:0.5.8: not found
```

Am I missing something?

**Comment by AlexGodbehere** [comment]
For anyone else coming up against this, I had configured the dependency incorrectly.

```yaml
- name: charts/switchboard
  version: 0.5.8
  repository: oci://ghcr.io/borchero
  condition: switchboard.enabled
```
