### ISSUE TITLE
Allow CNAME records for external-dns integration

### ISSUE THREAD

**Issue by 0x0013** [borchero/switchboard#15]
Hi again,

Many cloud providers provide their `LoadBalancer` resources with hostname only, and no IP addresses. The hostname is usually meant to be added as a CNAME record to DNS.

Example kubernetes service status:
```
status:
  loadBalancer:
    ingress:
    - hostname: example.lb.identifier.amazonaws.com
```

It would be useful if Switchboard would also be able to pick up a `hostname` variable in the absence of an IP address, from the defined traefik service object, and create the `DNSEndpoint` resource with `recordType: CNAME` in this case. I think external-dns does something like that from `ingress` sources.
