### ISSUE TITLE
Unable to support traefik match rules with `Header`

### ISSUE THREAD

**Issue by michael-robbins** [borchero/switchboard#185]
Switchboard throws this error:
```
ERROR	failed to parse hosts from ingress route	{"name": "argocd/argocd-ui", "error": "failed to parse domains: unsupported function: Header"}
```

When attempting to parse this IngressRoute:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ui
  annotations:
    cert-manager.io/cluster-issuer: my-issuer
    external-dns.alpha.kubernetes.io/hostname: argo.host.name
    kubernetes.io/ingress.class: ingress-private
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argo.host.name`)
      priority: 10
      services:
        - kind: Service
          name: argocd-server
          port: 443
    - kind: Rule
      match: Host(`argo.host.name`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - kind: Service
          name: argocd-server
          port: 443
          scheme: h2c
  tls:
    secretName: argocd-cert
```

Is there a way to enable support for Host detection with this style match rule? Or do I need to manually specify the domains via `.spec.tls.domains` myself?
