### ISSUE TITLE
Override default ExternalDNS target

### ISSUE THREAD

**Issue by Elegant996** [borchero/switchboard#36]
For our environment, we are always using a CNAME on the base domain instead of the `status.loadbalancer.IP` from the traefik service. Would it be possible to add an override for all ExternalDNS targets similar to how we must pick an Issuer for cert-manager?

**Comment by Elegant996** [comment]
Sure, see the ingress below:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  annotations:
    external-dns.alpha.kubernetes.io/target: example.com
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: test
            port:
              name: https
  tls:
  - hosts:
    - test.example.net
    secretName: test-example-tls
```

In this case, ExternalDNS would generate a CNAME entry for `test.example.com` that points to `example.com`. In our use case, all ingresses would use `example.com` as the target and never the loadbalancer IP since it is an internal address.

Thanks!
