### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by DerEnderKeks** [borchero/switchboard#5]
The ExternalDNS integration currently always creates `DNSEndpoints` with A records, even if the target IP is an IPv6 address. Instead either A or AAAA records should be created, depending on the target address family.

**Comment by borchero** [comment]
Hey @DerEnderKeks! I've never used IPv6 with Kubernetes ... can you give me an example of how the service's `.status` field looks like? Are IPv6 addresses simply appended to `.status.loadBalancer.ingress[]`?

**Comment by DerEnderKeks** [comment]
Yup, just like with IPv4:

```yaml
status:
  loadBalancer:
    ingress:
      - ip: 2001:db8::1
```
