### ISSUE TITLE
failed to upsert TLS certificate

### ISSUE THREAD

**Issue by th0th** [borchero/switchboard#84]
Greetings Oliver, first of all, thanks for making switchboard! 💐 

I have installed `0.5.7` with this config:

```yaml
integrations:
  certManager:
    certificateTemplate:
      spec:
        issuerRef:
          kind: ClusterIssuer
          name: letsencrypt-prod
    enabled: true
  externalDNS:
    enabled: true
    targetService:
      name: traefik
      namespace: kube-system
```

However, I see entries like this for all the `IngressRoute`s.

```
2023-03-05T02:23:45.692Z	ERROR	failed to upsert resource	{"name": "*/rest-api", "integration": "cert-manager", "error": "failed to upsert TLS certificate: admission webhook \"webhook.cert-manager.io\" denied the request: spec.issuerRef.name: Required value: must be specified"}
```

I also tried going with `certificateIssuer.create=true` but it resulted in the same error, as well.

After struggling for a long time _(this struggle includes giving`0.5.6` a go, too)_, I tried installing `0.5.5` and everything seems to be working now. 

P.S. I looked for the sponsor button on the repo, but no luck. Not something big but I would like to contribute  <3
